# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Коновалова Оксана Валерьевна'
tagline:          'Юрист'
description:      'Сообщество юристов<br/> Геленджик-Москва-Саратов'
url:              http://hyde.getpoole.com
baseurl:          /


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

