# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Коновалова Оксана Валерьевна'
tagline:          'Юрист'
description:      'Сайт сообщества юристов. Геленджик-Москва-Саратов'
url:              https://konovalova-jurist.ru
baseurl:          /


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

